### ISSUE TITLE
Significant Degradation in Timing with Utilization improvements

### ISSUE THREAD

**Issue by tpagarani** [QuickLogic-Corp/symbiflow-arch-defs#109]
Recently there have been PR merged to improve the Utilization.

https://github.com/QuickLogic-Corp/yosys/pull/10

There is significant degradation in Delay parameters like Critical path, TNS. 
I have attached the report with and without recent improvements in mux and pack. 

[07-28-2020_design_run_results.xlsx](https://github.com/QuickLogic-Corp/symbiflow-arch-defs/files/5047672/07-28-2020_design_run_results.xlsx)
[08-02-2020_design_run_results.xlsx](https://github.com/QuickLogic-Corp/symbiflow-arch-defs/files/5047673/08-02-2020_design_run_results.xlsx)

**Comment by mkurc-ant** [comment]
This issue can be mitigated by enabling LUT4 inference in ABC and increasing their cost via `abc -luts 1,2,2,4:8`. The drawback is increased pos-synthesis design sizes.

Here are the results: [results.xlsx](https://github.com/QuickLogic-Corp/symbiflow-arch-defs/files/5118205/results.xlsx)

**Comment by mkurc-ant** [comment]
Should have been fixed by https://github.com/QuickLogic-Corp/yosys/pull/14

**Comment by tpagarani** [comment]
This issue was fixed
