### ISSUE TITLE
Make install support for qlf_k6n10

### ISSUE THREAD

**Issue by kkumar23** [QuickLogic-Corp/symbiflow-arch-defs#322]
make install is failing for k6n10.
Also tool chain wrapper support is required for k6n10 till router.

**Comment by kkumar23** [comment]
Toolchain wrappers i have upadated https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/324 please review.
For k6n10 make install, does not install scripts and techmaps folders.
fasm is still not supported for k6n10.

**Comment by kkumar23** [comment]
@mkurc-ant : few more things to be added will be the package uploaded to have both k4n8 and k6n10 files. 
We need to provide build to customer today, so please consider this as priority.

**Comment by mkurc-ant** [comment]
@kkumar23 Ok, you can merge #324. I'll check and fix CI so that data files for k6n10 are included in the package
