### ISSUE TITLE
There is no support for PP3 BGA package.

### ISSUE THREAD

**Issue by anthonyle-ql** [QuickLogic-Corp/symbiflow-arch-defs#543]
We would like to have the tool to support PP3 BGA package to support design with high IO counts. The current WLCSP package only has 18 GPIOs.

**Comment by mkurc-ant** [comment]
@anthonyle-ql I've created a PR which adds the missing support: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/561

**Comment by mkurc-ant** [comment]
The PR https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/561 is merged so this issue should be considered as solved.

**Comment by anthonyle-ql** [comment]
Confirmed latest build supports PD64 package.
