### ISSUE TITLE
There is no bit file generated for both EOS S3 and PP3 device.

### ISSUE THREAD

**Issue by anthonyle-ql** [QuickLogic-Corp/symbiflow-arch-defs#562]
With the latest build, there is no bit file generated for either EOS S3 device or PP3 device. Without the bit file, I can't validate the output using PP3 HW.

**Comment by mkurc-ant** [comment]
@anthonyle-ql I've created a PR with a fix to the wrapper scripts. This should solve the problem: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/567

**Comment by anthonyle-ql** [comment]
The latest Symbiflow build generates bit file for PP3 and EOS S3 devices.
