### ISSUE TITLE
Generate both SPI Slave bit file and SPI Master bit file as default

### ISSUE THREAD

**Issue by anthonyle-ql** [QuickLogic-Corp/symbiflow-arch-defs#640]
Please help to add the feature to generate both bit files type, SPI Master and SPI Slave, as default. It is much easier to test SPI Slave file since it does not requires extra tool to program the flash device before the testing can start. Programming flash device that is installed on the PP3 EVK board is error prone.

**Comment by anthonyle-ql** [comment]
Hi, do you have an estimate timeline for when this feature is available? Thanks.

**Comment by lpawelcz** [comment]
Hi @anthonyle-ql,
this feature was introduced in https://github.com/QuickLogic-Corp/quicklogic-fasm/pull/21. From now on the bitstream generation process for PP3 should generate bitstreams in 3 different modes simultaneously:
* Enabled SPI master mode - it will have original file name
* Enabled SPI slave mode - original file name and "_spi_slave" substring
* No header and checksum - original file name and "_no_header_checksum" substring

I hope that helps you

**Comment by anthonyle-ql** [comment]
Confirmed that the latest daily build has created 3 different bit files as stated. The bit files failed to work correctly when tested with JB3 (the same board in Antmicro). Attached is the zip file that contains the followings:
1. RTL folder: 24bit counter design with the top 4 bits mapped to LEDs. One of the bit is mapped to the LED of the JB3.
2. Script: DOS Command script to execute commands to setup the JB3 device to load FPGA bit file. The IC that performs the USB to SPI function is Diolan. Please download the Diolan SW at "https://diolan.com/dln2"; for testing, we recommend to download the Windows SW package and install. The script calls a series of installed binaries to send the bit file to the PP3 device during FPGA configuration. The Diolan SW is "dln.3.4.0"; make sure to update the script with the bit file name before execution.
3. Folder 1110: contains the 3 generated bit files for (1) amd 1 mod file
a. jb4.bit = generated SPI master bit file; file is not tested.
b. jb4_mod.bit = modified of jb4.bit file to delete the first byte and zero out the second byte (to mimic the SPI Slave bit file); device is configured and function is not working.
c. jb4_spi_slave.bit = generated bit file; device is configured and function is not working.
d. jb4_no_header_checksum.bit = generated bit file; device is not configured and function is not working.
4. Folder 1104: contains the 1 generated bit file (SPI Master) for the build on November 4, 2021
a. jb4.bit = generated bit file; files is tested in master mode; not working due to 20MHz clock setting.
b. jb4_mod.bit = modified (1) file for SPI Slave configuration; device is configured and function is working.

Note: when the file contains the proper # of bits, the configuration using SPI Slave is OK.
[bitFiles.zip](https://github.com/QuickLogic-Corp/symbiflow-arch-defs/files/7543273/bitFiles.zip)

**Comment by lpawelcz** [comment]
After merging https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/683 and https://github.com/QuickLogic-Corp/quicklogic-fasm/pull/24 we were able to build SPI slave bit file that was tested on device. Hardware was configured successfully and the function was working.
The problem is in default bitstream that is overlaid by the actual design. For now this feature is disabled. Another fixes that were introduced are changes of PP3 assembler default settings to match command byte of the bistream (zeroing first byte of the bitstream for SPI slave bit file).

**Comment by anthonyle-ql** [comment]
Confirmed validation of both SPI Master file and SPI Slave file. The no CRC and CheckSum file does not configured the FPGA. Since PP3 configuration is done via SPI Slave or SPI Master, this item is completed.
