### ISSUE TITLE
Mechanism to select SPI CLK frequency for SPI Master bit file

### ISSUE THREAD

**Issue by anthonyle-ql** [QuickLogic-Corp/symbiflow-arch-defs#659]
The current generated bit file for PP3 device has selected SPI CLK frequency of 20MHz. Please add method to select SPI CLK frequency of 5MHz or 20MHz.

Some HW system may not support SPI CLK at 20MHz.

**Comment by lpawelcz** [comment]
PRs https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/683 and https://github.com/QuickLogic-Corp/quicklogic-fasm/pull/24 changed the default settings of PP3 assembler which include setting the SPI CLK frequency to 5MHz.

**Comment by anthonyle-ql** [comment]
Confirmed the default setting for SPI CLK in master mode is 5MHz. Will document how to change frequency using binaries tool.
