### ISSUE TITLE
 RAM/FIFO setup/hold/Tco modeled on ports instead of individual bits

### ISSUE THREAD

**Issue by tpagarani** [QuickLogic-Corp/symbiflow-arch-defs#67]
Quicklogic RAM/FIFO setup/hold/Tco timing has significant variation across different bits of Input and Output ports. 
Currently VPR models the timing for the whole port using max/min delays out of all the bits. 
It needs to be extended to support individual bit signal timing

**Comment by mkurc-ant** [comment]
This pull request should fix the issue: https://github.com/QuickLogic-Corp/symbiflow-arch-defs/pull/71

**Comment by tpagarani** [comment]
This has been fixed
